### ISSUE TITLE
Fails compilation

### ISSUE THREAD

**Issue by zandaqo** [brianlow/syntaxnet-docker#1]
Hi,

Not sure if it's the image or something with tensorflow itself, but it fails compilation for me:

```
ERROR: /root/.cache/bazel/_bazel_root/07e289e62ff0021383a4043a3fef5989/external/tf/tensorflow/core/kernels/BUILD:856:1: 
C++ compilation of rule '@tf//tensorflow/core/kernels:cwise_op' failed: 
gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now 
-Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 72 argument(s) skipped): 
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
____Building complete.
____Elapsed time: 129.185s, Critical Path: 101.70s
//syntaxnet:arc_standard_transitions_test                             NO STATUS
//syntaxnet:beam_reader_ops_test                                      NO STATUS
//syntaxnet:graph_builder_test                                        NO STATUS
//syntaxnet:lexicon_builder_test                                      NO STATUS
//syntaxnet:parser_features_test                                      NO STATUS
//syntaxnet:parser_trainer_test                                       NO STATUS
//syntaxnet:reader_ops_test                                           NO STATUS
//syntaxnet:sentence_features_test                                    NO STATUS
//syntaxnet:shared_store_test                                         NO STATUS
//syntaxnet:tagger_transitions_test                                   NO STATUS
//syntaxnet:text_formats_test                                         NO STATUS
//util/utf8:unicodetext_unittest                                      NO STATUS
Executed 0 out of 12 tests: 12 were skipped.
```

**Comment by brianlow** [comment]
DockerHub is failing to build as well. I've pushed a new version based on Ubuntu 15.10. It works locally. Will report back if DockerHub passes.

**Comment by salamanders** [comment]
Same here.  And this dockerfile seeks to be the one the news articles point to!

**Comment by zandaqo** [comment]
>  And this dockerfile seeks to be the one the news articles point to!

I'm not sure what you are referring to, but this negativity is uncalled for. As far as I can tell, this repository is not affiliated with SyntaxNet; @brianlow is just trying to do us service by sharing his docker image, for which I, for one, am grateful, no matter the result.

**Comment by salamanders** [comment]
Wait what?  No negativity intended, my apologies if I sounded that way.

What I meant was "and in a few news articles, the comments link to here, so you will have lots of happy people if/when you get it working!"

**Comment by brianlow** [comment]
Sorry all, no luck replicating the problem locally. I am no docker expert though. Maybe I am getting an old version of the ubuntu image or maybe a different apt package?

**Comment by brianlow** [comment]
A lead... https://github.com/brianlow/syntaxnet-docker/issues/1#issuecomment-219466747

**Comment by brianlow** [comment]
Based on the Tensorflow issue above, perhaps a larger amount of memory is needed to compile. I am running on OSX with the docker VM assigned 8GB.

**Comment by brianlow** [comment]
I've learned how to push my pre-built image to DockerHub. You can pull the image directly without compiling:

```
docker pull brianlow/syntaxnet-docker
echo "Name the boat" | docker run --rm -i brianlow/syntaxnet-docker
```

**Comment by brianlow** [comment]
Closing for now, feel free to re-open if this doesn't help.

**Comment by sublimino** [comment]
@brianlow example in README lists 

```
echo "Name this boat" | docker run --rm -i brianlow/syntaxnet
```

whereas it should either be

```
echo "Name this boat" | docker run --rm -i brianlow/syntaxnet-docker
```

or the pushed imaged tagged differently. Personal preference is dropping `-docker` from the name.
