### ISSUE TITLE
enhancement - support parsey-mcparseface api 

### ISSUE THREAD

**Issue by johndpope** [brianlow/syntaxnet-docker#3]
Thanks for this - 

fyi - this repo 
https://github.com/dmansfield/parsey-mcparseface-api has additional code to allow serving up results via an api

There's also this 
https://github.com/dan-nadler/ParseyAPI

@dsindex has included some code to patch repos
https://github.com/dmansfield/parsey-mcparseface-api/issues/1

I spent a couple of days trying to get this working with docker but no joy.
https://gist.githubusercontent.com/johndpope/fc1c2327a4ae255d9c44dda9b67b5288/raw/5b0923fd2565cd86a6d76c09ddc563fc53959447/parseyapi.sh

**Comment by brianlow** [comment]
Great idea! I won't have time to work on this. Patches welcome if you have any luck. Thanks! 

What symptoms did you have?

**Comment by johndpope** [comment]
hi - sorry for tardy reply - 
I made this
https://github.com/johndpope/DockerParseyMcParsefaceAPI
going to close this.
I'm looking to interact with tensorflow with grpc if there's interest - hit me up.
